In [15]:
# Actividad 06
import dask
import time
import pandas as pd
import numpy as np

In [16]:
%%time
matriz = np.ones((10,10,10))
matriz

CPU times: total: 0 ns
Wall time: 0 ns

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [19]:
%%time
import dask.array as da

matriz = da.ones((100,100,100))
matriz

CPU times: total: 0 ns
Wall time: 516 Âµs

dask.array<ones_like, shape=(100, 100, 100), dtype=float64, chunksize=(100, 100, 100), chunktype=numpy.ndarray>

In [20]:
matriz.compute()

array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       ...,

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]])

# 1 - Pandas

In [25]:
%%time
!pip install pyarrow
!pip install fastparquet

Requirement already satisfied: pyarrow in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (12.0.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from pyarrow) (1.24.3)

WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: fastparquet in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (2023.4.0)
Requirement already satisfied: numpy>=1.20.3 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from fastparquet) (1.24.3)
Requirement already satisfied: fsspec in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from fastparquet) (2023.5.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from fastparquet) (2.0.1)
Requirement already satisfied: cramjam>=2.3 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from fastparquet) (2.6.2)
Requirement already satisfied: packaging in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from fastparquet) (21.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.5.0->fastparquet) (2022.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.5.0->fastparquet) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.5.0->fastparquet) (2.8.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from packaging->fastparquet) (3.0.7)
Requirement already satisfied: six>=1.5 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.16.0)
CPU times: total: 15.6 ms
Wall time: 3.11 s

WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
df_pandas_1 = pd.read_parquet("yellow_tripdata_2018-01.parquet")

In [27]:
df_pandas_1.shape[0]

8760687

In [32]:
%%time
# Pandas read
# Primero necesito generar el csv
df_pandas_pkt=pd.read_parquet("yellow_tripdata_2018-02.parquet")
df_pandas_pkt.to_csv("yellow_tripdata_2018-02.csv")

CPU times: total: 1min 3s
Wall time: 1min

In [34]:
%%time
df_pandas_csv=pd.read_csv("yellow_tripdata_2018-02.csv")

CPU times: total: 12.2 s
Wall time: 12.2 s

In [35]:
print(df_pandas_csv.shape[0])

8492819

In [36]:
%%time
# Parquet read 
df_pandas_pkt = pd.read_parquet("yellow_tripdata_2018-02.parquet")

CPU times: total: 4.73 s
Wall time: 1.06 s

In [37]:
df_pandas_csv.head()

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,0,1,2018-02-01 00:01:58,2018-02-01 00:04:03,1,0.0,1,N,145,145,2,3.5,0.5,0.5,0.0,0.0,0.3,4.8,NaN,NaN
1,1,1,2018-02-01 00:56:48,2018-02-01 00:57:42,1,2.9,1,N,145,145,2,2.5,0.5,0.5,0.0,0.0,0.3,3.8,NaN,NaN
2,2,1,2018-02-01 00:04:42,2018-02-01 00:19:32,1,5.8,1,N,236,119,2,18.5,0.5,0.5,0.0,0.0,0.3,19.8,NaN,NaN
3,3,1,2018-02-01 00:38:10,2018-02-01 00:40:16,1,0.3,1,N,82,82,2,3.5,0.5,0.5,0.0,0.0,0.3,4.8,NaN,NaN
4,4,1,2018-02-01 00:43:03,2018-02-01 00:59:26,2,2.6,1,N,82,7,1,13.0,0.5,0.5,1.0,0.0,0.3,15.3,NaN,NaN

In [38]:
%%time
df_pandas_csv.describe()

CPU times: total: 3.86 s
Wall time: 3.86 s

,Unnamed: 0,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
count,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,0.0,0.0
mean,4.246409e+06,1.562332e+00,1.596185e+00,2.769982e+00,1.037533e+00,1.637890e+02,1.621691e+02,1.302302e+00,1.221812e+01,3.265125e-01,4.976250e-01,1.828238e+00,3.029421e-01,2.996056e-01,1.547609e+01,NaN,NaN
std,2.451666e+06,4.960995e-01,1.247619e+00,3.572887e+00,4.478767e-01,6.627971e+01,7.015142e+01,4.787164e-01,1.118283e+01,4.495976e-01,4.261004e-02,2.457048e+00,1.688060e+00,1.461870e-02,1.373858e+01,NaN,NaN
min,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-4.630000e+02,-4.500000e+00,-5.000000e-01,-3.224200e+02,-1.676000e+01,-3.000000e-01,-4.638000e+02,NaN,NaN
25%,2.123204e+06,1.000000e+00,1.000000e+00,9.200000e-01,1.000000e+00,1.140000e+02,1.130000e+02,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,3.000000e-01,8.300000e+00,NaN,NaN
50%,4.246409e+06,2.000000e+00,1.000000e+00,1.580000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,9.000000e+00,0.000000e+00,5.000000e-01,1.450000e+00,0.000000e+00,3.000000e-01,1.130000e+01,NaN,NaN
75%,6.369614e+06,2.000000e+00,2.000000e+00,2.880000e+00,1.000000e+00,2.330000e+02,2.340000e+02,2.000000e+00,1.350000e+01,5.000000e-01,5.000000e-01,2.360000e+00,0.000000e+00,3.000000e-01,1.680000e+01,NaN,NaN
max,8.492818e+06,2.000000e+00,1.920000e+02,1.061200e+03,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,2.759070e+03,9.664000e+01,3.280000e+01,4.411100e+02,9.808000e+02,1.000000e+00,2.759370e+03,NaN,NaN

In [39]:
%%time
df_pandas_pkt.describe()

CPU times: total: 3.83 s
Wall time: 3.83 s

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,8.492819e+06,8492819,8492819,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06
mean,1.562332e+00,2018-02-14 21:12:42.859370240,2018-02-14 21:28:27.493817344,1.596185e+00,2.769982e+00,1.037533e+00,1.637890e+02,1.621691e+02,1.302302e+00,1.221812e+01,3.265125e-01,4.976250e-01,1.828238e+00,3.029421e-01,2.996056e-01,1.547609e+01
min,1.000000e+00,2008-12-31 12:43:55,2008-12-31 12:49:55,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-4.630000e+02,-4.500000e+00,-5.000000e-01,-3.224200e+02,-1.676000e+01,-3.000000e-01,-4.638000e+02
25%,1.000000e+00,2018-02-07 21:35:03.500000,2018-02-07 21:48:50,1.000000e+00,9.200000e-01,1.000000e+00,1.140000e+02,1.130000e+02,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,3.000000e-01,8.300000e+00
50%,2.000000e+00,2018-02-14 18:38:57,2018-02-14 18:55:11,1.000000e+00,1.580000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,9.000000e+00,0.000000e+00,5.000000e-01,1.450000e+00,0.000000e+00,3.000000e-01,1.130000e+01
75%,2.000000e+00,2018-02-22 02:02:43,2018-02-22 02:23:55.500000,2.000000e+00,2.880000e+00,1.000000e+00,2.330000e+02,2.340000e+02,2.000000e+00,1.350000e+01,5.000000e-01,5.000000e-01,2.360000e+00,0.000000e+00,3.000000e-01,1.680000e+01
max,2.000000e+00,2031-02-13 17:36:35,2031-02-13 17:45:36,1.920000e+02,1.061200e+03,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,2.759070e+03,9.664000e+01,3.280000e+01,4.411100e+02,9.808000e+02,1.000000e+00,2.759370e+03
std,4.960995e-01,NaN,NaN,1.247619e+00,3.572887e+00,4.478767e-01,6.627971e+01,7.015142e+01,4.787164e-01,1.118283e+01,4.495976e-01,4.261004e-02,2.457048e+00,1.688060e+00,1.461870e-02,1.373858e+01

In [43]:
%%time
df_pandas_pkt.groupby("passenger_count").tip_amount.mean()

CPU times: total: 141 ms
Wall time: 146 ms

passenger_count
0      1.753507
1      1.834925
2      1.824387
3      1.781126
4      1.679214
5      1.848603
6      1.824732
7      5.020333
8      7.868333
9      4.241250
192    1.460000
Name: tip_amount, dtype: float64

In [40]:
%%time
df_long = pd.concat([df_pandas_1, df_pandas_csv], axis=0)

CPU times: total: 15.1 s
Wall time: 15.1 s

In [41]:
%%time
df_long.describe()

CPU times: total: 18.6 s
Wall time: 18.7 s

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Unnamed: 0
count,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,12.0,12.0,8.492819e+06
mean,1.561645e+00,1.601579e+00,2.787266e+00,1.038555e+00,1.641286e+02,1.624524e+02,1.306522e+00,1.223148e+01,3.255862e-01,4.975649e-01,1.823425e+00,3.027764e-01,2.996183e-01,1.548371e+01,2.5,0.0,4.246409e+06
std,4.961854e-01,1.253127e+00,4.575936e+01,4.464508e-01,6.632128e+01,7.023327e+01,4.802928e-01,1.143964e+01,4.499327e-01,4.297859e-02,2.471987e+00,1.713694e+00,1.452192e-02,1.397243e+01,0.0,0.0,2.451666e+06
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-4.630000e+02,-4.469000e+01,-5.000000e-01,-3.224200e+02,-1.676000e+01,-3.000000e-01,-4.638000e+02,2.5,0.0,0.000000e+00
25%,1.000000e+00,1.000000e+00,9.200000e-01,1.000000e+00,1.140000e+02,1.130000e+02,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,3.000000e-01,8.300000e+00,2.5,0.0,2.123204e+06
50%,2.000000e+00,1.000000e+00,1.560000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,9.000000e+00,0.000000e+00,5.000000e-01,1.400000e+00,0.000000e+00,3.000000e-01,1.130000e+01,2.5,0.0,4.246409e+06
75%,2.000000e+00,2.000000e+00,2.860000e+00,1.000000e+00,2.340000e+02,2.340000e+02,2.000000e+00,1.350000e+01,5.000000e-01,5.000000e-01,2.350000e+00,0.000000e+00,3.000000e-01,1.664000e+01,2.5,0.0,6.369614e+06
max,2.000000e+00,1.920000e+02,1.894838e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,8.016000e+03,9.664000e+01,4.549000e+01,4.417100e+02,9.808000e+02,1.000000e+00,8.016800e+03,2.5,0.0,8.492818e+06

In [42]:
%%time
df_long.groupby("passenger_count").tip_amount.mean()

CPU times: total: 312 ms
Wall time: 289 ms

passenger_count
0      1.747349
1      1.829148
2      1.824561
3      1.775899
4      1.675837
5      1.842066
6      1.822703
7      5.757681
8      5.974524
9      5.178537
192    1.460000
Name: tip_amount, dtype: float64

# 2-  Dask

In [45]:
%%time
import dask.dataframe as dd

CPU times: total: 125 ms
Wall time: 311 ms

In [47]:
%%time
df_dask_csv = dd.read_csv("yellow_tripdata_2018-02.csv")

CPU times: total: 15.6 ms
Wall time: 11 ms

In [49]:
%%time
df_dask_parquet = dd.read_parquet("yellow_tripdata_2018-02.parquet")

CPU times: total: 0 ns
Wall time: 33.9 ms

In [50]:
%%time
df_long_dask = pd.concat([df_pandas_1, df_pandas_csv], axis=0)

CPU times: total: 14.5 s
Wall time: 14.6 s

In [55]:
%%time
df_long_dask.groupby("passenger_count").tip_amount.mean()

CPU times: total: 297 ms
Wall time: 289 ms

passenger_count
0      1.747349
1      1.829148
2      1.824561
3      1.775899
4      1.675837
5      1.842066
6      1.822703
7      5.757681
8      5.974524
9      5.178537
192    1.460000
Name: tip_amount, dtype: float64

In [56]:
%%time
df_long_dask.describe()

CPU times: total: 16.3 s
Wall time: 16.5 s

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Unnamed: 0
count,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,12.0,12.0,8.492819e+06
mean,1.561645e+00,1.601579e+00,2.787266e+00,1.038555e+00,1.641286e+02,1.624524e+02,1.306522e+00,1.223148e+01,3.255862e-01,4.975649e-01,1.823425e+00,3.027764e-01,2.996183e-01,1.548371e+01,2.5,0.0,4.246409e+06
std,4.961854e-01,1.253127e+00,4.575936e+01,4.464508e-01,6.632128e+01,7.023327e+01,4.802928e-01,1.143964e+01,4.499327e-01,4.297859e-02,2.471987e+00,1.713694e+00,1.452192e-02,1.397243e+01,0.0,0.0,2.451666e+06
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-4.630000e+02,-4.469000e+01,-5.000000e-01,-3.224200e+02,-1.676000e+01,-3.000000e-01,-4.638000e+02,2.5,0.0,0.000000e+00
25%,1.000000e+00,1.000000e+00,9.200000e-01,1.000000e+00,1.140000e+02,1.130000e+02,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,3.000000e-01,8.300000e+00,2.5,0.0,2.123204e+06
50%,2.000000e+00,1.000000e+00,1.560000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,9.000000e+00,0.000000e+00,5.000000e-01,1.400000e+00,0.000000e+00,3.000000e-01,1.130000e+01,2.5,0.0,4.246409e+06
75%,2.000000e+00,2.000000e+00,2.860000e+00,1.000000e+00,2.340000e+02,2.340000e+02,2.000000e+00,1.350000e+01,5.000000e-01,5.000000e-01,2.350000e+00,0.000000e+00,3.000000e-01,1.664000e+01,2.5,0.0,6.369614e+06
max,2.000000e+00,1.920000e+02,1.894838e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,8.016000e+03,9.664000e+01,4.549000e+01,4.417100e+02,9.808000e+02,1.000000e+00,8.016800e+03,2.5,0.0,8.492818e+06

In [57]:
%%time
df_dask_csv.describe()

CPU times: total: 93.8 ms
Wall time: 117 ms

Dask DataFrame Structure:
              Unnamed: 0 VendorID passenger_count trip_distance RatecodeID PULocationID DOLocationID payment_type fare_amount    extra  mta_tax tip_amount tolls_amount improvement_surcharge total_amount congestion_surcharge airport_fee
npartitions=1
                 float64  float64         float64       float64    float64      float64      float64      float64     float64  float64  float64    float64      float64               float64      float64              float64     float64
                     ...      ...             ...           ...        ...          ...          ...          ...         ...      ...      ...        ...          ...                   ...          ...                  ...         ...
Dask Name: describe-numeric, 73 graph layers

In [51]:
%%time
df_dask_parquet.describe()

CPU times: total: 141 ms
Wall time: 158 ms

Dask DataFrame Structure:
              VendorID tpep_pickup_datetime tpep_dropoff_datetime passenger_count trip_distance RatecodeID PULocationID DOLocationID payment_type fare_amount    extra  mta_tax tip_amount tolls_amount improvement_surcharge total_amount
npartitions=1
               float64               object                object         float64       float64    float64      float64      float64      float64     float64  float64  float64    float64      float64               float64      float64
                   ...                  ...                   ...             ...           ...        ...          ...          ...          ...         ...      ...      ...        ...          ...                   ...          ...
Dask Name: describe, 294 graph layers

In [53]:
%%time
df_dask_csv.describe()

CPU times: total: 78.1 ms
Wall time: 75.8 ms

Dask DataFrame Structure:
              Unnamed: 0 VendorID passenger_count trip_distance RatecodeID PULocationID DOLocationID payment_type fare_amount    extra  mta_tax tip_amount tolls_amount improvement_surcharge total_amount congestion_surcharge airport_fee
npartitions=1
                 float64  float64         float64       float64    float64      float64      float64      float64     float64  float64  float64    float64      float64               float64      float64              float64     float64
                     ...      ...             ...           ...        ...          ...          ...          ...         ...      ...      ...        ...          ...                   ...          ...                  ...         ...
Dask Name: describe-numeric, 73 graph layers

In [52]:
%%time
df_dask_parquet.describe().compute()

CPU times: total: 20.5 s
Wall time: 11.9 s

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,8.492819e+06,8492819,8492819,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06,8.492819e+06
min,1.000000e+00,2008-12-31 12:43:55,2008-12-31 12:49:55,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-4.630000e+02,-4.500000e+00,-5.000000e-01,-3.224200e+02,-1.676000e+01,-3.000000e-01,-4.638000e+02
25%,1.000000e+00,2018-02-07 21:35:03.500000,2018-02-07 21:48:50,1.000000e+00,9.200000e-01,1.000000e+00,1.140000e+02,1.130000e+02,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,3.000000e-01,8.300000e+00
50%,2.000000e+00,2018-02-14 18:38:57,2018-02-14 18:55:11,1.000000e+00,1.580000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,9.000000e+00,0.000000e+00,5.000000e-01,1.450000e+00,0.000000e+00,3.000000e-01,1.130000e+01
75%,2.000000e+00,2018-02-22 02:02:43,2018-02-22 02:23:55.500000,2.000000e+00,2.880000e+00,1.000000e+00,2.330000e+02,2.340000e+02,2.000000e+00,1.350000e+01,5.000000e-01,5.000000e-01,2.360000e+00,0.000000e+00,3.000000e-01,1.680000e+01
max,2.000000e+00,2031-02-13 17:36:35,2031-02-13 17:45:36,1.920000e+02,1.061200e+03,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,2.759070e+03,9.664000e+01,3.280000e+01,4.411100e+02,9.808000e+02,1.000000e+00,2.759370e+03
mean,1.562332e+00,NaN,NaN,1.596185e+00,2.769982e+00,1.037533e+00,1.637890e+02,1.621691e+02,1.302302e+00,1.221812e+01,3.265125e-01,4.976250e-01,1.828238e+00,3.029421e-01,2.996056e-01,1.547609e+01
std,4.960995e-01,NaN,NaN,1.247619e+00,3.572887e+00,4.478767e-01,6.627971e+01,7.015142e+01,4.787164e-01,1.118283e+01,4.495976e-01,4.261004e-02,2.457048e+00,1.688060e+00,1.461870e-02,1.373858e+01

In [ ]:
%%time
print(df_dask_csv.tprep_dropoff_datetime.value_counts().compute())

# 3 - VAEX

In [59]:
%%time
!pip install vaex


import vaex as vx

Collecting vaex
  Downloading vaex-4.16.0-py3-none-any.whl (4.7 kB)
Collecting vaex-server<0.9,>=0.8.1
  Downloading vaex_server-0.8.1-py3-none-any.whl (23 kB)
Collecting vaex-hdf5<0.15,>=0.13.0
  Downloading vaex_hdf5-0.14.1-py3-none-any.whl (16 kB)
Collecting vaex-ml<0.19,>=0.18.1
  Downloading vaex_ml-0.18.1-py3-none-any.whl (58 kB)
     ---------------------------------------- 58.2/58.2 kB 1.0 MB/s eta 0:00:00
Collecting vaex-astro<0.10,>=0.9.3
  Downloading vaex_astro-0.9.3-py3-none-any.whl (20 kB)
Collecting vaex-viz<0.6,>=0.5.4
  Downloading vaex_viz-0.5.4-py3-none-any.whl (19 kB)
Collecting vaex-core<4.17,>=4.16.0
  Downloading vaex_core-4.16.1-cp310-cp310-win_amd64.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 2.5 MB/s eta 0:00:00
Collecting vaex-jupyter<0.9,>=0.8.1
  Downloading vaex_jupyter-0.8.1-py3-none-any.whl (43 kB)
     ---------------------------------------- 43.2/43.2 kB 2.1 MB/s eta 0:00:00
Collecting astropy
  Downloading astropy-5.3-cp310-cp310-win_amd64.whl (6.9 MB)
     ---------------------------------------- 6.9/6.9 MB 1.8 MB/s eta 0:00:00
Collecting aplus
  Downloading aplus-0.11.0.tar.gz (3.7 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: requests in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (2.28.1)
Requirement already satisfied: nest-asyncio>=1.3.3 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (1.5.4)
Requirement already satisfied: pyarrow>=5.0.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (12.0.0)
Requirement already satisfied: filelock in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (3.4.2)
Collecting progressbar2
  Downloading progressbar2-4.2.0-py2.py3-none-any.whl (27 kB)
Requirement already satisfied: numpy>=1.16 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (1.24.3)
Requirement already satisfied: six in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (1.16.0)
Requirement already satisfied: cloudpickle in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (2.2.1)
Requirement already satisfied: frozendict!=2.2.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (2.3.4)
Requirement already satisfied: future>=0.15.2 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (0.18.2)
Collecting tabulate>=0.8.3
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting pydantic>=1.8.0
  Downloading pydantic-1.10.8-cp310-cp310-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 3.4 MB/s eta 0:00:00
Collecting rich
  Downloading rich-13.4.1-py3-none-any.whl (239 kB)
     -------------------------------------- 239.4/239.4 kB 2.9 MB/s eta 0:00:00
Collecting blake3
  Downloading blake3-0.3.3-cp310-none-win_amd64.whl (207 kB)
     -------------------------------------- 207.8/207.8 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: pyyaml in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (6.0)
Requirement already satisfied: dask!=2022.4.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (2023.5.1)
Requirement already satisfied: pandas in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-core<4.17,>=4.16.0->vaex) (2.0.1)
Collecting h5py>=2.9
  Downloading h5py-3.8.0-cp310-cp310-win_amd64.whl (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 3.2 MB/s eta 0:00:00
Collecting ipyvolume>=0.4
  Downloading ipyvolume-0.6.1-py3-none-any.whl (1.6 MB)
     ---------------------------------------- 1.6/1.6 MB 3.3 MB/s eta 0:00:00
Collecting ipyleaflet
  Downloading ipyleaflet-0.17.3-py3-none-any.whl (3.4 MB)
     ---------------------------------------- 3.4/3.4 MB 2.7 MB/s eta 0:00:00
Collecting xarray
  Downloading xarray-2023.5.0-py3-none-any.whl (994 kB)
     -------------------------------------- 994.3/994.3 kB 3.3 MB/s eta 0:00:00
Collecting ipympl
  Downloading ipympl-0.9.3-py2.py3-none-any.whl (511 kB)
     -------------------------------------- 511.6/511.6 kB 3.2 MB/s eta 0:00:00
Collecting bqplot>=0.10.1
  Downloading bqplot-0.12.39-py2.py3-none-any.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 3.3 MB/s eta 0:00:00
Collecting ipyvuetify<2,>=1.2.2
  Downloading ipyvuetify-1.8.10-py2.py3-none-any.whl (11.7 MB)
     ---------------------------------------- 11.7/11.7 MB 2.9 MB/s eta 0:00:00
Requirement already satisfied: jinja2 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-ml<0.19,>=0.18.1->vaex) (3.0.3)
Requirement already satisfied: traitlets in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-ml<0.19,>=0.18.1->vaex) (5.1.1)
Collecting numba
  Downloading numba-0.57.0-cp310-cp310-win_amd64.whl (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 3.3 MB/s eta 0:00:00
Collecting cachetools
  Downloading cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Requirement already satisfied: tornado>4.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-server<0.9,>=0.8.1->vaex) (6.1)
Collecting uvicorn[standard]
  Downloading uvicorn-0.22.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 58.3/58.3 kB 3.0 MB/s eta 0:00:00
Collecting fastapi
  Downloading fastapi-0.95.2-py3-none-any.whl (56 kB)
     -------------------------------------- 57.0/57.0 kB 994.3 kB/s eta 0:00:00
Requirement already satisfied: matplotlib>=1.3.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-viz<0.6,>=0.5.4->vaex) (3.7.1)
Requirement already satisfied: pillow in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from vaex-viz<0.6,>=0.5.4->vaex) (9.0.1)
Requirement already satisfied: ipywidgets<9,>=7.5.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (7.6.5)
Collecting traittypes>=0.0.6
  Downloading traittypes-0.2.1-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: toolz>=0.10.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from dask!=2022.4.0->vaex-core<4.17,>=4.16.0->vaex) (0.12.0)
Requirement already satisfied: fsspec>=2021.09.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from dask!=2022.4.0->vaex-core<4.17,>=4.16.0->vaex) (2023.5.0)
Requirement already satisfied: importlib-metadata>=4.13.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from dask!=2022.4.0->vaex-core<4.17,>=4.16.0->vaex) (6.6.0)
Requirement already satisfied: packaging>=20.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from dask!=2022.4.0->vaex-core<4.17,>=4.16.0->vaex) (21.3)
Requirement already satisfied: click>=8.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from dask!=2022.4.0->vaex-core<4.17,>=4.16.0->vaex) (8.0.3)
Requirement already satisfied: partd>=1.2.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from dask!=2022.4.0->vaex-core<4.17,>=4.16.0->vaex) (1.4.0)
Collecting ipyvue>=1.7.0
  Downloading ipyvue-1.9.1-py2.py3-none-any.whl (2.7 MB)
     ---------------------------------------- 2.7/2.7 MB 3.0 MB/s eta 0:00:00
Collecting pythreejs>=2.4.0
  Downloading pythreejs-2.4.2-py3-none-any.whl (3.4 MB)
     ---------------------------------------- 3.4/3.4 MB 1.9 MB/s eta 0:00:00
Collecting ipywebrtc
  Downloading ipywebrtc-0.6.0-py2.py3-none-any.whl (260 kB)
     -------------------------------------- 260.7/260.7 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=1.3.1->vaex-viz<0.6,>=0.5.4->vaex) (3.0.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=1.3.1->vaex-viz<0.6,>=0.5.4->vaex) (1.0.7)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=1.3.1->vaex-viz<0.6,>=0.5.4->vaex) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=1.3.1->vaex-viz<0.6,>=0.5.4->vaex) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=1.3.1->vaex-viz<0.6,>=0.5.4->vaex) (4.29.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=1.3.1->vaex-viz<0.6,>=0.5.4->vaex) (1.3.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from pandas->vaex-core<4.17,>=4.16.0->vaex) (2022.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from pandas->vaex-core<4.17,>=4.16.0->vaex) (2022.7.1)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from pydantic>=1.8.0->vaex-core<4.17,>=4.16.0->vaex) (4.4.0)
Collecting pyerfa>=2.0
  Downloading pyerfa-2.0.0.3-cp310-cp310-win_amd64.whl (347 kB)
     -------------------------------------- 347.7/347.7 kB 2.4 MB/s eta 0:00:00
Collecting starlette<0.28.0,>=0.27.0
  Downloading starlette-0.27.0-py3-none-any.whl (66 kB)
     ---------------------------------------- 67.0/67.0 kB 1.8 MB/s eta 0:00:00
Collecting xyzservices>=2021.8.1
  Downloading xyzservices-2023.5.0-py3-none-any.whl (56 kB)
     ---------------------------------------- 56.5/56.5 kB 2.9 MB/s eta 0:00:00
Collecting branca>=0.5.0
  Downloading branca-0.6.0-py3-none-any.whl (24 kB)
Requirement already satisfied: ipython-genutils in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.2.0)
Requirement already satisfied: ipython<9 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (8.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from jinja2->vaex-ml<0.19,>=0.18.1->vaex) (2.1.2)
Collecting llvmlite<0.41,>=0.40.0dev0
  Downloading llvmlite-0.40.0-cp310-cp310-win_amd64.whl (27.7 MB)
     ---------------------------------------- 27.7/27.7 MB 2.9 MB/s eta 0:00:00
Collecting python-utils>=3.0.0
  Downloading python_utils-3.6.0-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from requests->vaex-core<4.17,>=4.16.0->vaex) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from requests->vaex-core<4.17,>=4.16.0->vaex) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from requests->vaex-core<4.17,>=4.16.0->vaex) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from requests->vaex-core<4.17,>=4.16.0->vaex) (1.26.11)
Collecting pygments<3.0.0,>=2.13.0
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting markdown-it-py<3.0.0,>=2.2.0
  Downloading markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
     ---------------------------------------- 84.5/84.5 kB 2.3 MB/s eta 0:00:00
Collecting h11>=0.8
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Requirement already satisfied: colorama>=0.4 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from uvicorn[standard]->vaex-server<0.9,>=0.8.1->vaex) (0.4.4)
Collecting websockets>=10.4
  Downloading websockets-11.0.3-cp310-cp310-win_amd64.whl (124 kB)
     -------------------------------------- 124.7/124.7 kB 3.7 MB/s eta 0:00:00
Collecting python-dotenv>=0.13
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting httptools>=0.5.0
  Downloading httptools-0.5.0-cp310-cp310-win_amd64.whl (142 kB)
     -------------------------------------- 143.0/143.0 kB 4.3 MB/s eta 0:00:00
Collecting watchfiles>=0.13
  Downloading watchfiles-0.19.0-cp37-abi3-win_amd64.whl (270 kB)
     -------------------------------------- 270.9/270.9 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: zipp>=0.5 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=4.13.0->dask!=2022.4.0->vaex-core<4.17,>=4.16.0->vaex) (3.15.0)
Requirement already satisfied: backcall in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (65.5.0)
Requirement already satisfied: pickleshare in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.7.5)
Requirement already satisfied: decorator in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (3.0.26)
Requirement already satisfied: stack-data in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.1.4)
Requirement already satisfied: black in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (22.1.0)
Requirement already satisfied: matplotlib-inline in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.1.3)
Requirement already satisfied: jedi>=0.16 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.18.1)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (6.8.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (3.5.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (1.0.2)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (5.1.3)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: locket in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from partd>=1.2.0->dask!=2022.4.0->vaex-core<4.17,>=4.16.0->vaex) (1.0.0)
Collecting ipydatawidgets>=1.1.1
  Downloading ipydatawidgets-4.3.3-py2.py3-none-any.whl (271 kB)
     -------------------------------------- 271.7/271.7 kB 3.4 MB/s eta 0:00:00
Collecting anyio<5,>=3.4.0
  Downloading anyio-3.7.0-py3-none-any.whl (80 kB)
     ---------------------------------------- 80.9/80.9 kB 4.4 MB/s eta 0:00:00
Collecting exceptiongroup
  Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting sniffio>=1.1
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (1.5.1)
Requirement already satisfied: jupyter-client<8.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (7.1.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.8.3)
Requirement already satisfied: jupyter-core in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0->ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (4.9.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0->ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (4.4.0)
Requirement already satisfied: wcwidth in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets<9,>=7.5.0->bqplot>=0.10.1->vaex-jupyter<0.9,>=0.8.1->vaex) (6.4.8)
Requirement already satisfied: platformdirs>=2 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from black->ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (2.4.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from black->ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.4.3)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from black->ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.9.0)
Requirement already satisfied: tomli>=1.1.0 in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from black->ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (2.0.0)
Requirement already satisfied: pure-eval in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.2.2)
Requirement already satisfied: executing in c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython<9->ipympl->vaex-jupyter<0.9,>=0.8.1->vaex) (0.8.2)

WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
  DEPRECATION: aplus is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
    WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\joaquinleon\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

CPU times: total: 938 ms
Wall time: 1min 26s

In [60]:
%%time
df_vaex_csv = vx.read_csv("yellow_tripdata_2018-02.csv", convert = True, chunk_size=5_000_000)

CPU times: total: 22 s
Wall time: 25.8 s

In [64]:
%%time
df_vaex_prkt = vx.open("yellow_tripdata_2018-02.parquet")

CPU times: total: 0 ns
Wall time: 6 ms

In [65]:
%%time
df_vaex_prkt.describe()

NotImplementedError: Cannot convert null

In [66]:
%%time
df_vaex_csv.describe()

CPU times: total: 14.2 s
Wall time: 2.15 s

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
data_type,int64,int64,string,string,int64,float64,int64,string,int64,int64,int64,float64,float64,float64,float64,float64,float64,float64,float64,float64
count,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,8492819,0,0
NA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8492819,8492819
mean,4246409.0,1.5623324834781007,--,--,1.596185082950667,2.7699821437381513,1.0375332383746787,--,163.78895794199784,162.16914996069033,1.3023017445679697,12.218117773380099,0.3265124618810307,0.49762499471612426,1.828238243391768,0.302942110270075,0.2996056079788268,15.476090766943283,nan,nan
std,2451665.667917,0.496099,--,--,1.247619,3.572887,0.447877,--,66.279709,70.151414,0.478716,11.182828,0.449598,0.04261,2.457048,1.68806,0.014619,13.738576,NaN,NaN
min,0,1,--,--,0,0.0,1,--,1,1,1,-463.0,-4.5,-0.5,-322.42,-16.76,-0.3,-463.8,inf,inf
max,8492818,2,--,--,192,1061.2,99,--,265,265,4,2759.07,96.64,32.8,441.11,980.8,1.0,2759.37,-inf,-inf

In [67]:
%%time
df_long_vaex = pd.concat([df_pandas_1, df_pandas_csv], axis=0)

CPU times: total: 20.1 s
Wall time: 20.2 s

In [69]:
%%time
df_vaex_csv.head(5)

CPU times: total: 0 ns
Wall time: 1 ms

  #    Unnamed: 0    VendorID  tpep_pickup_datetime    tpep_dropoff_datetime      passenger_count    trip_distance    RatecodeID  store_and_fwd_flag      PULocationID    DOLocationID    payment_type    fare_amount    extra    mta_tax    tip_amount    tolls_amount    improvement_surcharge    total_amount    congestion_surcharge    airport_fee
  0             0           1  2018-02-01 00:01:58     2018-02-01 00:04:03                      1              0               1  N                                145             145               2            3.5      0.5        0.5             0               0                      0.3             4.8                     nan            nan
  1             1           1  2018-02-01 00:56:48     2018-02-01 00:57:42                      1              2.9             1  N                                145             145               2            2.5      0.5        0.5             0               0                      0.3             3.8                     nan            nan
  2             2           1  2018-02-01 00:04:42     2018-02-01 00:19:32                      1              5.8             1  N                                236             119               2           18.5      0.5        0.5             0               0                      0.3            19.8                     nan            nan
  3             3           1  2018-02-01 00:38:10     2018-02-01 00:40:16                      1              0.3             1  N                                 82              82               2            3.5      0.5        0.5             0               0                      0.3             4.8                     nan            nan
  4             4           1  2018-02-01 00:43:03     2018-02-01 00:59:26                      2              2.6             1  N                                 82               7               1           13        0.5        0.5             1               0                      0.3            15.3                     nan            nan

In [71]:
%%time
df_long_vaex.describe()

CPU times: total: 13.9 s
Wall time: 14 s

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Unnamed: 0
count,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,1.725351e+07,12.0,12.0,8.492819e+06
mean,1.561645e+00,1.601579e+00,2.787266e+00,1.038555e+00,1.641286e+02,1.624524e+02,1.306522e+00,1.223148e+01,3.255862e-01,4.975649e-01,1.823425e+00,3.027764e-01,2.996183e-01,1.548371e+01,2.5,0.0,4.246409e+06
std,4.961854e-01,1.253127e+00,4.575936e+01,4.464508e-01,6.632128e+01,7.023327e+01,4.802928e-01,1.143964e+01,4.499327e-01,4.297859e-02,2.471987e+00,1.713694e+00,1.452192e-02,1.397243e+01,0.0,0.0,2.451666e+06
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-4.630000e+02,-4.469000e+01,-5.000000e-01,-3.224200e+02,-1.676000e+01,-3.000000e-01,-4.638000e+02,2.5,0.0,0.000000e+00
25%,1.000000e+00,1.000000e+00,9.200000e-01,1.000000e+00,1.140000e+02,1.130000e+02,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,3.000000e-01,8.300000e+00,2.5,0.0,2.123204e+06
50%,2.000000e+00,1.000000e+00,1.560000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,9.000000e+00,0.000000e+00,5.000000e-01,1.400000e+00,0.000000e+00,3.000000e-01,1.130000e+01,2.5,0.0,4.246409e+06
75%,2.000000e+00,2.000000e+00,2.860000e+00,1.000000e+00,2.340000e+02,2.340000e+02,2.000000e+00,1.350000e+01,5.000000e-01,5.000000e-01,2.350000e+00,0.000000e+00,3.000000e-01,1.664000e+01,2.5,0.0,6.369614e+06
max,2.000000e+00,1.920000e+02,1.894838e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,8.016000e+03,9.664000e+01,4.549000e+01,4.417100e+02,9.808000e+02,1.000000e+00,8.016800e+03,2.5,0.0,8.492818e+06

In [72]:
%%time
df_long_vaex.groupby("passenger_count").tip_amount.mean()

CPU times: total: 328 ms
Wall time: 327 ms

passenger_count
0      1.747349
1      1.829148
2      1.824561
3      1.775899
4      1.675837
5      1.842066
6      1.822703
7      5.757681
8      5.974524
9      5.178537
192    1.460000
Name: tip_amount, dtype: float64